export const province = [
  {
    id: 1,
    provinceCode: "10",
    provinceName: "กรุงเทพมหานคร",
    geoId: 2,
  },
  { id: 2, provinceCode: "11", provinceName: "สมุทรปราการ", geoId: 2 },
  { id: 3, provinceCode: "12", provinceName: "นนทบุรี", geoId: 2 },
  { id: 4, provinceCode: "13", provinceName: "ปทุมธานี", geoId: 2 },
  {
    id: 5,
    provinceCode: "14",
    provinceName: "พระนครศรีอยุธยา",
    geoId: 2,
  },
  { id: 6, provinceCode: "15", provinceName: "อ่างทอง", geoId: 2 },
  { id: 7, provinceCode: "16", provinceName: "ลพบุรี", geoId: 2 },
  { id: 8, provinceCode: "17", provinceName: "สิงห์บุรี", geoId: 2 },
  { id: 9, provinceCode: "18", provinceName: "ชัยนาท", geoId: 2 },
  { id: 10, provinceCode: "19", provinceName: "สระบุรี", geoId: 2 },
  { id: 11, provinceCode: "20", provinceName: "ชลบุรี", geoId: 5 },
  { id: 12, provinceCode: "21", provinceName: "ระยอง", geoId: 5 },
  { id: 13, provinceCode: "22", provinceName: "จันทบุรี", geoId: 5 },
  { id: 14, provinceCode: "23", provinceName: "ตราด", geoId: 5 },
  { id: 15, provinceCode: "24", provinceName: "ฉะเชิงเทรา", geoId: 5 },
  { id: 16, provinceCode: "25", provinceName: "ปราจีนบุรี", geoId: 5 },
  { id: 17, provinceCode: "26", provinceName: "นครนายก", geoId: 2 },
  { id: 18, provinceCode: "27", provinceName: "สระแก้ว", geoId: 5 },
  { id: 19, provinceCode: "30", provinceName: "นครราชสีมา", geoId: 3 },
  { id: 20, provinceCode: "31", provinceName: "บุรีรัมย์", geoId: 3 },
  { id: 21, provinceCode: "32", provinceName: "สุรินทร์", geoId: 3 },
  { id: 22, provinceCode: "33", provinceName: "ศรีสะเกษ", geoId: 3 },
  { id: 23, provinceCode: "34", provinceName: "อุบลราชธานี", geoId: 3 },
  { id: 24, provinceCode: "35", provinceName: "ยโสธร", geoId: 3 },
  { id: 25, provinceCode: "36", provinceName: "ชัยภูมิ", geoId: 3 },
  { id: 26, provinceCode: "37", provinceName: "อำนาจเจริญ", geoId: 3 },
  { id: 27, provinceCode: "39", provinceName: "หนองบัวลำภู", geoId: 3 },
  { id: 28, provinceCode: "40", provinceName: "ขอนแก่น", geoId: 3 },
  { id: 29, provinceCode: "41", provinceName: "อุดรธานี", geoId: 3 },
  { id: 30, provinceCode: "42", provinceName: "เลย", geoId: 3 },
  { id: 31, provinceCode: "43", provinceName: "หนองคาย", geoId: 3 },
  { id: 32, provinceCode: "44", provinceName: "มหาสารคาม", geoId: 3 },
  { id: 33, provinceCode: "45", provinceName: "ร้อยเอ็ด", geoId: 3 },
  { id: 34, provinceCode: "46", provinceName: "กาฬสินธุ์", geoId: 3 },
  { id: 35, provinceCode: "47", provinceName: "สกลนคร", geoId: 3 },
  { id: 36, provinceCode: "48", provinceName: "นครพนม", geoId: 3 },
  { id: 37, provinceCode: "49", provinceName: "มุกดาหาร", geoId: 3 },
  { id: 38, provinceCode: "50", provinceName: "เชียงใหม่", geoId: 1 },
  { id: 39, provinceCode: "51", provinceName: "ลำพูน", geoId: 1 },
  { id: 40, provinceCode: "52", provinceName: "ลำปาง", geoId: 1 },
  { id: 41, provinceCode: "53", provinceName: "อุตรดิตถ์", geoId: 1 },
  { id: 42, provinceCode: "54", provinceName: "แพร่", geoId: 1 },
  { id: 43, provinceCode: "55", provinceName: "น่าน", geoId: 1 },
  { id: 44, provinceCode: "56", provinceName: "พะเยา", geoId: 1 },
  { id: 45, provinceCode: "57", provinceName: "เชียงราย", geoId: 1 },
  { id: 46, provinceCode: "58", provinceName: "แม่ฮ่องสอน", geoId: 1 },
  { id: 47, provinceCode: "60", provinceName: "นครสวรรค์", geoId: 2 },
  { id: 48, provinceCode: "61", provinceName: "อุทัยธานี", geoId: 2 },
  { id: 49, provinceCode: "62", provinceName: "กำแพงเพชร", geoId: 2 },
  { id: 50, provinceCode: "63", provinceName: "ตาก", geoId: 4 },
  { id: 51, provinceCode: "64", provinceName: "สุโขทัย", geoId: 2 },
  { id: 52, provinceCode: "65", provinceName: "พิษณุโลก", geoId: 2 },
  { id: 53, provinceCode: "66", provinceName: "พิจิตร", geoId: 2 },
  { id: 54, provinceCode: "67", provinceName: "เพชรบูรณ์", geoId: 2 },
  { id: 55, provinceCode: "70", provinceName: "ราชบุรี", geoId: 4 },
  { id: 56, provinceCode: "71", provinceName: "กาญจนบุรี", geoId: 4 },
  { id: 57, provinceCode: "72", provinceName: "สุพรรณบุรี", geoId: 2 },
  { id: 58, provinceCode: "73", provinceName: "นครปฐม", geoId: 2 },
  { id: 59, provinceCode: "74", provinceName: "สมุทรสาคร", geoId: 2 },
  { id: 60, provinceCode: "75", provinceName: "สมุทรสงคราม", geoId: 2 },
  { id: 61, provinceCode: "76", provinceName: "เพชรบุรี", geoId: 4 },
  {
    id: 62,
    provinceCode: "77",
    provinceName: "ประจวบคีรีขันธ์",
    geoId: 4,
  },
  {
    id: 63,
    provinceCode: "80",
    provinceName: "นครศรีธรรมราช",
    geoId: 6,
  },
  { id: 64, provinceCode: "81", provinceName: "กระบี่", geoId: 6 },
  { id: 65, provinceCode: "82", provinceName: "พังงา", geoId: 6 },
  { id: 66, provinceCode: "83", provinceName: "ภูเก็ต", geoId: 6 },
  {
    id: 67,
    provinceCode: "84",
    provinceName: "สุราษฎร์ธานี",
    geoId: 6,
  },
  { id: 68, provinceCode: "85", provinceName: "ระนอง", geoId: 6 },
  { id: 69, provinceCode: "86", provinceName: "ชุมพร", geoId: 6 },
  { id: 70, provinceCode: "90", provinceName: "สงขลา", geoId: 6 },
  { id: 71, provinceCode: "91", provinceName: "สตูล", geoId: 6 },
  { id: 72, provinceCode: "92", provinceName: "ตรัง", geoId: 6 },
  { id: 73, provinceCode: "93", provinceName: "พัทลุง", geoId: 6 },
  { id: 74, provinceCode: "94", provinceName: "ปัตตานี", geoId: 6 },
  { id: 75, provinceCode: "95", provinceName: "ยะลา", geoId: 6 },
  { id: 76, provinceCode: "96", provinceName: "นราธิวาส", geoId: 6 },
  { id: 77, provinceCode: "97", provinceName: "บึงกาฬ", geoId: 3 },
];
